stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lawr/myruby:${CICD_GIT_COMMIT}
- name: test
  steps:
  - runScriptConfig:
      image: codeclimate/codeclimate:0.83.0
      shellScript: /usr/src/app/bin/codeclimate
  - runScriptConfig:
      image: gliderlabs/herokuish:latest
      shellScript: |-
        setup_test_db
        cp -R . /tmp/app
        /bin/herokuish buildpack test
timeout: 60
notification: {}
